/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-11 at 04:34:02 UTC 
 * Modify at your own risk.
 */

package com.appspot.dingx_askaround.questions.model;

/**
 * Model definition for Question.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the questions. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Question extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> comments;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String content;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("create_date")
  private java.lang.String createDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String entityKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> options;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("question_type")
  private java.lang.String questionType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("valid_days") @com.google.api.client.json.JsonString
  private java.lang.Long validDays;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> votes;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getComments() {
    return comments;
  }

  /**
   * @param comments comments or {@code null} for none
   */
  public Question setComments(java.util.List<java.lang.String> comments) {
    this.comments = comments;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContent() {
    return content;
  }

  /**
   * @param content content or {@code null} for none
   */
  public Question setContent(java.lang.String content) {
    this.content = content;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreateDate() {
    return createDate;
  }

  /**
   * @param createDate createDate or {@code null} for none
   */
  public Question setCreateDate(java.lang.String createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEntityKey() {
    return entityKey;
  }

  /**
   * @param entityKey entityKey or {@code null} for none
   */
  public Question setEntityKey(java.lang.String entityKey) {
    this.entityKey = entityKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getOptions() {
    return options;
  }

  /**
   * @param options options or {@code null} for none
   */
  public Question setOptions(java.util.List<java.lang.String> options) {
    this.options = options;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuestionType() {
    return questionType;
  }

  /**
   * @param questionType questionType or {@code null} for none
   */
  public Question setQuestionType(java.lang.String questionType) {
    this.questionType = questionType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getValidDays() {
    return validDays;
  }

  /**
   * @param validDays validDays or {@code null} for none
   */
  public Question setValidDays(java.lang.Long validDays) {
    this.validDays = validDays;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getVotes() {
    return votes;
  }

  /**
   * @param votes votes or {@code null} for none
   */
  public Question setVotes(java.util.List<java.lang.Long> votes) {
    this.votes = votes;
    return this;
  }

  @Override
  public Question set(String fieldName, Object value) {
    return (Question) super.set(fieldName, value);
  }

  @Override
  public Question clone() {
    return (Question) super.clone();
  }

}
